format: yamanifest
version: 1.0
---
work/accessom2_restart.nml:
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/accessom2_restart.nml
  hashes:
    binhash: 43ac57a7eadc1ca2b586deab4e2bb7b3
    md5: f68b393d72a31638fd524fc3a406b313
work/ice/RESTART/grid.nc:
  copy: true
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ice/grid.nc
  hashes:
    binhash: e4f106149f7fd8cf265b68f237bd1689
    md5: 1213e346055ee073fe33dc12578d99c6
work/ice/RESTART/i2o.nc:
  copy: true
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ice/i2o.nc
  hashes:
    binhash: 23adb000cfffbceba7a2453b2a77098c
    md5: 81d8458f31c080d160f32be43c2293ef
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ice/ice.restart_file
  hashes:
    binhash: a25e3fea4a7b9950ae7c45ad66736683
    md5: 24c5f01b17c1c5ebd05fd452407f11ee
work/ice/RESTART/iced.2396-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ice/iced.2396-01-01-00000.nc
  hashes:
    binhash: f997cb204df580b19131a916994b671e
    md5: 276cbaee14d8badfdf56362160d749c0
work/ice/RESTART/iced.2397-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ice/iced.2397-01-01-00000.nc
  hashes:
    binhash: 388dbdfe618c4c3b0d94aa7ed005c3fd
    md5: 2c160f861748f629aeaca6cdc9b0a2b7
work/ice/RESTART/iced.2398-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ice/iced.2398-01-01-00000.nc
  hashes:
    binhash: f5792e853fa55363ba96ababc2042144
    md5: 31e4a038bcc18bb3f225105eef90ff77
work/ice/RESTART/iced.2399-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ice/iced.2399-01-01-00000.nc
  hashes:
    binhash: 69c6f890095255c2f765aa1441350ec1
    md5: a9ec0714fb72c23c710ce173ed5aee8f
work/ice/RESTART/iced.2400-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ice/iced.2400-01-01-00000.nc
  hashes:
    binhash: 93c0321aa40084657808d450ea254563
    md5: ad7cd9caf15327ca22e3f1fa288609bc
work/ice/RESTART/kmt.nc:
  copy: true
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ice/kmt.nc
  hashes:
    binhash: 11d59c5cb3bf6bc4145ebb6c3b25d702
    md5: 1f9806c646a620378e5257e480bc9df7
work/ice/RESTART/monthly_sstsss.nc:
  copy: true
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ice/monthly_sstsss.nc
  hashes:
    binhash: 92e05524008af7d0e07bc9e58c0f2a74
    md5: 323d4c605f83f4d7d3126da70153c2ed
work/ice/RESTART/o2i.nc:
  copy: true
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ice/o2i.nc
  hashes:
    binhash: d8a17b6fa5259715a325095bb0d2ea60
    md5: 5046928b001e8cee4626f5bb74a2ab57
work/ice/RESTART/sicemass.nc:
  copy: true
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ice/sicemass.nc
  hashes:
    binhash: df7335e04953966e4df29f4349456f17
    md5: b9f246abc90e93fecbc0192ddea20b51
work/ice/RESTART/u_star.nc:
  copy: true
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ice/u_star.nc
  hashes:
    binhash: 5e980748c80551a47045f3fa5dbb4fa5
    md5: 63a8a46242ba7c82263d805ea618a1f0
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ocean/ocean_age.res.nc
  hashes:
    binhash: 1d1230f19916684d0311867abd38987d
    md5: a8d1009f00f386e87fef308b23d9e08e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c3d66d700097467b02db9a56ae1bd400
    md5: 78175b7801a49b3577cd03a4fd386b21
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 34b93e19eec2070b0c080140a4286f5e
    md5: e41b3b166e65d517a6bb321d9a7cf489
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ocean/ocean_density.res.nc
  hashes:
    binhash: 0d38687d77b40819634b2ec93c3e69d7
    md5: f21d87a97da1b67c740a15eed1eafeaa
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 987b3fc3c6348329229ab688e44fedb5
    md5: c19b811210c778a47133e68c2f8bad60
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ab38a3d706503c28749cb5f3c5d7ebb9
    md5: d4446b304d046e599ae6e556b177af2b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b8b75703c2b420c9324260a5447f64f5
    md5: 28b2d74357d990fe46a70bb224634c06
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b8e12b95a897f528baf7ff5490aa022a
    md5: 22edeb101dc5610bb15a2e9ab70df20e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b95c169a9ea746074a877dfea4999177
    md5: 614361280ceafa0addaa6e17453d7e17
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 626543ea3bdce673297c77d8d9bffd89
    md5: 264857a545f23069085d0a9f84f1d1ef
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ocean/ocean_solo.res
  hashes:
    binhash: f653b5ce68533add4da5fc1011a9c3d7
    md5: 5d00eea1315f6eb297d22eb03a449622
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6e191689997322134981994f2c2756f5
    md5: ed340802b0dde9fb533f88ac482e64e5
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e677b374d2aba320ac1a8392d9e33e05
    md5: cf7466c9c34ab9b7b9304df9933f1f29
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ocean/ocean_tracer.res
  hashes:
    binhash: c3c6944345ba5634b9a26ba477143fe8
    md5: 32bee3152a2a2f63b67d25a7eaeaae61
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7f348550416b4a88f334708011a03af6
    md5: d1409ce9e54b550f9edb5db43852bd09
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/mp2135/access-om2/archive/1deg_jra55_ryf_RCPcool_humid_x2/restart099/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: bd411524643ff491e01038415a395333
    md5: 8423be82e11e8b0a5647af1ad2cd86f2
